markdown:           kramdown #redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

permalink:           pretty

# Setup
title:               '#datalove'
tagline:             ''
description:         ''
home:                http://loopingleo.github.io
url:                 http://loopingleo.github.io/blog
baseurl:             /blog/
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
name:              Leonhard Raßl
url:               http://loopingleo.github.io
email:             LeonhardRassl@gmail.com

# Custom vars
version:             1.0.0

## This is the list of pages to include in the header of the website.
pages_list:
  About: '/blog/about'
  Atom: '/blog/atom.xml'
  RSS: '/blog/rss.xml'
